# -*- coding: utf-8 -*-
"""023 converting scanned PDFs to excel for accounting

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/danshorstein/a6f1039d73a1f9bf150f3f71e2c33801/023-converting-scanned-pdfs-to-excel-for-accounting.ipynb
"""



import os

import requests
import pdfplumber

def download_file():
    local_filename = 'voice-prescription-master/prescription1.pdf'

    with requests.get() as r:
        assert r.status_code == 200, f'error, status code is {r.status_code}'
        with open(local_filename, 'wb') as f:
            f.write(r.content)

    return local_filename

#invoice = ''voice-prescription-master/prescription1.pdf
invoice_pdf = 'D:/Voice prescription 4/voice-prescription-master/prescription1.pdf'

#invoice_pdf

with pdfplumber.open(invoice_pdf) as pdf:
    page = pdf.pages[0]
    text = page.extract_text()
    print(text)

os.system(f'ocrmypdf {invoice_pdf} output.pdf')

with pdfplumber.open('output.pdf') as pdf:
    page = pdf.pages[0]
    text = page.extract_text(x_tolerance=2)
    print(text)

lines = text.split('\n')


import re
amt_re = re.compile(r'\.\d\d$')
medicine=""

for line in lines:
    if ('AF' in line or 'BF'in line ) :
        break
    if amt_re.search(line):
        medicine=line.split()[0]


print(medicine)

print(lines)
